# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juandr08
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-hands-on
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-crud-project # Es como decir el nombre de nuestro proyecto

provider: # Es en donde sera subida nuestra funcion
  name: aws # En este caso sera a AWS
  runtime: nodejs20.x # El interprete sera nodejs 20
  region: us-east-2

functions: # Seccion funciones es como si fuera un enrutador, donde asignamos todas las propiedades y rutas de nuestra API
  hello: # Agrupador de nuestra funcion
    handler: handler.hello # Ruta de donde se encuentra la funcion
    events:
      - httpApi: # Configurar la ruta http (metodos y ruta)
          path: / # Ruta
          method: get # MEtodo
